### ISSUE TITLE
Register the package?

### ISSUE THREAD

**Issue by nathanaelbosch** [filtron/FiniteHorizonGramians.jl#12]
Do you plan to register this package so that it can be installed and depended on more easily? Or are there still things that need to be done beforehand for the initial release?

**Comment by filtron** [comment]
Registering would in principle be fine but currently the package contains a lot of  "paper-code", that is superfluous for someone just wanting to compute a couple of Gramians. More specifically, the contents of the following folders need to be removed from main:   

``` 
FiniteHorizonGramians.jl/error_analysis
FiniteHorizonGramians.jl/legendre_coefficients
FiniteHorizonGramians.jl/numerical_experiments
```

However, the contents of these folders need to be preserved for the purpose of reproducibility and also to calculate optimal scaling parameters for different number types (i.e. a ```Float32``` algorithm should probably be implemented as well). Currently there's a separate branch ```paper-code```, which might be a fine way of storing both the "research" and "consumer" versions of the package?

**Comment by filtron** [comment]
In 3 days.
